[workspace]
members = [
    "entity",
    "farcaster-client",
    "indexer",
    "migration",
    "service"
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
chrono = "0.4"
lapin = "2.3"
