[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.0.0-rc.7", features = ["runtime-tokio-rustls", "sqlx-postgres", "with-chrono", "with-time"] }
serde = { version = "1", features = ["derive"] }
chrono = { workspace = true }
