[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.12.15", features = ["runtime-tokio-rustls", "sqlx-postgres", "with-chrono", "with-time", "postgres-array"] }
serde = { version = "1", features = ["derive"] }
chrono = { workspace = true }
