[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
lapin = "2.3.4"
prost = "0.12"
prost-types = "0.12"
tonic = "0.11"
tokio = { workspace = true }
anyhow = { workspace = true }

[build-dependencies]
tonic-build = "0.11"
