//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "casts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fid: i64,
    pub parent_fid: Option<i64>,
    #[sea_orm(column_type = "Text", unique)]
    pub hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub root_parent_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub root_parent_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_url: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub embeds: Json,
    pub mentions: Json,
    pub mentions_positions: Json,
    pub create_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub timestamp: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub pruned_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
