//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fids")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fid: i64,
    pub register_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub custody_address: String,
    #[sea_orm(column_type = "Text")]
    pub recovery_address: String,
    pub create_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
