//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hubs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub gossip_address: String,
    #[sea_orm(column_type = "Text")]
    pub rpc_address: String,
    pub excluded_hashes: Vec<String>,
    pub count: i32,
    #[sea_orm(column_type = "Text")]
    pub hub_version: String,
    #[sea_orm(column_type = "Text")]
    pub network: String,
    #[sea_orm(column_type = "Text")]
    pub app_version: String,
    pub timestamp: i32,
    pub create_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
