//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "signers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fid: i64,
    pub requester_fid: i64,
    pub key_type: i64,
    pub metadata_type: i32,
    #[sea_orm(column_type = "Text")]
    pub key: String,
    pub metadata: Json,
    pub create_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub added_at: DateTimeWithTimeZone,
    pub removed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
