//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "verifications")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fid: i64,
    #[sea_orm(column_type = "Text")]
    pub hash: String,
    #[sea_orm(column_type = "Text")]
    pub signer_address: String,
    #[sea_orm(column_type = "Text")]
    pub block_hash: String,
    #[sea_orm(column_type = "Text")]
    pub signature: String,
    pub create_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub timestamp: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
